<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>ASK.Server.Modules.ToDo</RootNamespace>
    <AssemblyName>ASK.Server.Modules.ToDo</AssemblyName>
  </PropertyGroup>

</Project>
